'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,CheckCircle2,FlaskConical,ShieldCheck,Zap} from 'lucide-react';
import {api,apiUrl,Data,fmt,post} from '@/lib/api';
import {Badge,PageHeading,useWorkspace} from './workspace';
import {EvidenceCard,SourceBadge} from './evidence-pages';
import EngineeringChart from './engineering-chart';

const steps=['The problem','Test request','Configuration','Evidence','Alternatives','Trial feedback','Summary'];

export default function JudgeMode(){
  const w=useWorkspace();
  const [step,setStep]=useState(0),[judge,setJudge]=useState<Data|null>(null),[objects,setObjects]=useState<Data[]>([]),[draft,setDraft]=useState<Data>(w.inputs),[review,setReview]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[trial,setTrial]=useState<Data|null>(null),[origin,setOrigin]=useState('generated_stress_test'),[stock,setStock]=useState(''),[requestEdited,setRequestEdited]=useState(false);
  useEffect(()=>{api('/api/test-objects').then(d=>setObjects(d.objects)).catch(e=>setError(e.message))},[]);
  useEffect(()=>{let alive=true;setJudge(null);setTrial(null);if(w.run)api(`/api/runs/${w.run.id}/judge`).then(d=>{if(alive)setJudge(d)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[w.run]);
  useEffect(()=>{if(w.run&&!requestEdited)setDraft(w.run.inputs)},[w.run,requestEdited]);
  const candidate=judge?.candidates?.[w.selected]||judge?.candidates?.[0];
  const change=(key:string,value:any)=>{setDraft({...draft,[key]:value,confirm_reference_mismatch:false});setReview(null);setRequestEdited(true)};
  async function recommend(){setLoading(true);setError('');try{
    const values={...draft,inventory_override:stock.trim()?JSON.parse(stock):draft.inventory_override};
    const check=await post('/api/test-objects/validate',values);setReview(check);
    if(check.confirmation_required)return;
    const result=await w.optimize(values);if(result){setJudge(await api(`/api/runs/${result.id}/judge`));setRequestEdited(false);setStep(2)}
  }catch(e){setError((e as Error).message)}finally{setLoading(false)}}
  async function upload(file:File,source:string){if(!judge||!candidate)return;setLoading(true);setError('');try{const form=new FormData();form.append('file',file);form.append('run_id',judge.id);form.append('candidate_id',candidate.id);form.append('source_type',source);setTrial(await api('/api/trials/upload',{method:'POST',body:form}));setJudge(await api(`/api/runs/${judge.id}/judge`))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
  async function demonstrate(){if(!judge||!candidate)return;setLoading(true);setError('');try{const response=await fetch(apiUrl(`/api/runs/${judge.id}/demo-waveform?candidate_id=${candidate.id}`));if(!response.ok)throw new Error('Generated waveform request failed');await upload(new File([await response.blob()],'generated-demonstration.csv',{type:'text/csv'}),'generated_stress_test')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
  const activeTrial=trial?.candidate_id===candidate?.id?trial:judge?.trials?.find((t:Data)=>t.candidate_id===candidate?.id);
  const selectedProfile=w.profiles.find(p=>p.id===draft.profile_id);
  return <div className="judge-mode"><PageHeading title="From request to evidence" description="A guided 4–6 minute tour of an inspectable generator setup." tag="JUDGE MODE" action={<Link className="button secondary" href="/">Engineering workspace</Link>}/>
    <nav className="judge-steps" aria-label="Demonstration steps">{steps.map((s,i)=><button key={s} aria-current={i===step?'step':undefined} className={i===step?'active':''} disabled={i>1&&(!judge||requestEdited)} onClick={()=>setStep(i)}><span>{i+1}</span>{s}</button>)}</nav>
    {(error||w.error)&&<div className="alert" role="alert">{error||w.error}</div>}
    <section className="judge-stage" aria-live="polite">
      {step===0&&<div className="judge-intro"><div className="judge-symbol"><Zap size={40}/></div><Badge tone="cyan">PHYSICS-GUIDED DECISION SUPPORT</Badge><h2>A stronger starting setup.<br/>An inspectable reason why.</h2><p>Impulse testing can require repeated physical changes to resistor networks and active generator stages.</p><div className="judge-flow">{['Analytical estimate','Adjust hardware','Trial shot','Inspect waveform','Repeat'].map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span>{s}</div>)}</div><p className="judge-goal">ImpulseTwin combines physics, counted hardware and supported ML correction before the next physical trial.</p><small>Simulation and synthetic benchmarks are available. Measured laboratory accuracy remains pending until new captures are evaluated.</small></div>}
      {step===1&&<div className="judge-request"><div><Badge>01 / DEFINE THE TEST</Badge><h2>What impulse is needed?</h2><p>Choose the source profile and test conditions. Unknown equipment references stay unknown.</p><div className="judge-fields"><label>Impulse type<select value={draft.impulse_type} onChange={e=>{setDraft({...draft,impulse_type:e.target.value,test_object_id:null,confirm_reference_mismatch:false});setRequestEdited(true);setReview(null)}}><option>Lightning</option><option>Switching</option></select></label><label>Requested crest (kV)<input type="number" min="1" value={draft.test_kv} onChange={e=>change('test_kv',Number(e.target.value))}/></label><label>Generator profile<select value={draft.profile_id} onChange={e=>change('profile_id',e.target.value)}>{w.profiles.map(p=><option value={p.id} key={p.id} disabled={!p.enabled}>{p.name}{!p.enabled?' — incomplete':''}</option>)}</select></label><label>Object capacitance (pF)<input type="number" min="1" value={draft.load_c_pf} onChange={e=>change('load_c_pf',Number(e.target.value))}/></label><label>Optional equipment reference<select value={draft.test_object_id||''} onChange={e=>change('test_object_id',e.target.value||null)}><option value="">No catalog selection</option>{objects.filter(o=>o.impulse_type===draft.impulse_type).map(o=><option key={o.id} value={o.id}>{o.name} — {o.status.toUpperCase()}</option>)}</select></label><label className="judge-checkbox"><input type="checkbox" checked={draft.require_model_agreement} onChange={e=>change('require_model_agreement',e.target.checked)}/> Search for agreement across both models</label></div>
      <details className="judge-advanced"><summary>Advanced parameters and operator reference</summary><div className="judge-fields">{[['divider_c_pf','Divider C (pF)'],['stray_c_pf','Stray C (pF)'],['l_uh','Inductance (µH)'],['efficiency','Efficiency'],['uncertainty_pct','Parasitic variation (%)']].map(([key,label])=><label key={key}>{label}<input type="number" step="any" value={draft[key]} onChange={e=>change(key,Number(e.target.value))}/></label>)}<label>Layout ID<input value={draft.layout_id} onChange={e=>change('layout_id',e.target.value)}/></label><label>Operator reference (kV)<input type="number" value={draft.equipment_reference_kv??''} onChange={e=>change('equipment_reference_kv',e.target.value?Number(e.target.value):null)}/></label><label>Reference source<input value={draft.equipment_reference_source||''} onChange={e=>change('equipment_reference_source',e.target.value||null)}/></label></div><label>Inventory override (JSON, optional)<textarea rows={4} value={stock} placeholder={'{"front":[{"ohm":30,"count_per_stage":1}],"tail":[{"ohm":520,"count_per_stage":1}],"provenance":"Operator supplied stock"}'} onChange={e=>{setStock(e.target.value);setRequestEdited(true)}}/></label></details>
      {selectedProfile?.units_per_value_per_stage==null&&<div className="alert compact">Unknown stock quantities. Enter actual operator inventory in Advanced parameters before optimization.</div>}
      {review&&<div className="reference-review"><Badge tone="amber">{review.status.toUpperCase().replaceAll('_',' ')}</Badge><p>{review.message}</p>{review.mismatch&&<label className="judge-checkbox"><input type="checkbox" checked={!!draft.confirm_reference_mismatch} onChange={e=>setDraft({...draft,confirm_reference_mismatch:e.target.checked})}/> I confirm that the requested test level is intentional.</label>}</div>}
      <button className="button primary" disabled={loading||w.busy} onClick={recommend}>{loading||w.busy?'Evaluating counted hardware…':'Find a starting configuration'}<ArrowRight size={16}/></button></div></div>}
      {step===2&&candidate&&<><div className="judge-stage-heading"><Badge>02 / COUNTED HARDWARE</Badge><h2>{candidate.compliance.nominal_pass?'A feasible simulated starting point':'Diagnostic alternative — waveform outside limits'}</h2><p>Run {judge?.id} · {judge?.profile.name} · {judge?.inputs.impulse_type}</p></div><div className="judge-config"><div><div className="judge-numbers"><div><strong>{candidate.settings.stages}</strong><span>active stages</span></div><div><strong>{fmt(candidate.settings.charge_kv_stage)}</strong><span>kV per stage</span></div></div>{[['Front',candidate.front_network],['Tail',candidate.tail_network]].map(([name,network])=><div className="judge-network" key={String(name)}><span>{String(name)} resistor / stage · {fmt((network as Data).equivalent_ohm)} Ω</span><strong>{(network as Data).topology}</strong><small>{(network as Data).total_components} components across all stages</small></div>)}<p>{candidate.setup_component_count} total components · {fmt(candidate.settings.stored_energy_kj)} kJ · {fmt(candidate.settings.stage_utilization*100)}% stage-voltage utilization</p></div><div><EngineeringChart waveform={candidate.waveform} target={judge?.target_waveform} circuit={candidate.circuit_crosscheck?.waveform} height={310}/><div className="judge-metrics">{[['front_us','Front / peak','µs'],['tail_us','Tail','µs'],['crest_kv','Crest','kV']].map(([key,label,unit])=><div key={key}><span>{label}</span><strong>{fmt(candidate.hybrid[key],3)} <small>{unit}</small></strong></div>)}</div></div></div><p className="judge-caveat">Counted construction and declared ratings checked. Actual pulse ratings, mounting and allowed physical connections still need verification.</p></>}
      {step===3&&candidate&&<><div className="judge-stage-heading"><Badge>03 / CHALLENGE THE RECOMMENDATION</Badge><h2>What supports this setup?</h2><p>Evidence is explicit. Disagreement and missing measurements remain visible.</p></div><EvidenceCard evidence={candidate.evidence}/><div className="judge-intervals"><h3>Prediction envelope</h3>{['Front / peak µs','Tail µs','Crest kV'].map((label,i)=><p key={label}>{label}: <strong>{fmt(candidate.uncertainty.lower[i],3)} – {fmt(candidate.uncertainty.upper[i],3)}</strong></p>)}<small>{candidate.uncertainty.method}. {candidate.uncertainty.coverage_limit}</small></div></>}
      {step===4&&judge&&<><div className="judge-stage-heading"><Badge>04 / COMPARE REAL TRADE-OFFS</Badge><h2>More than one useful starting point.</h2><p>{judge.alternative_scope}</p></div><div className="judge-alternatives">{judge.alternatives.map((a:Data)=><article key={a.candidate.id}>{a.labels.map((label:string)=><Badge key={label} tone="cyan">{label}</Badge>)}<h3>{a.candidate.settings.stages} stages · {fmt(a.candidate.settings.charge_kv_stage,1)} kV</h3><p>{a.candidate.setup_component_count} components</p><p>Waveform error cost: {fmt(a.candidate.accuracy_cost,4)}</p><p>Stage headroom: {fmt(a.candidate.settings.voltage_margin_kv_stage)} kV</p><Badge tone={a.candidate.compliance.nominal_pass?'green':'red'}>{a.candidate.compliance.nominal_pass?'NOMINAL PASS':'DIAGNOSTIC FAIL'}</Badge><p className="evidence-detail">Circuit: {a.candidate.circuit_crosscheck?.compliance.nominal_pass?'PASS':a.candidate.circuit_crosscheck?'FAIL':'NOT VERIFIED'}</p><button className="button secondary" onClick={()=>{w.setSelected(judge.candidates.findIndex((c:Data)=>c.id===a.candidate.id));setStep(2)}}>Inspect this setup</button></article>)}</div><Link className="button text-button" href="/compare/">Compare changes from a saved physical setup <ArrowRight size={14}/></Link></>}
      {step===5&&candidate&&<><div className="judge-stage-heading"><Badge>05 / CLOSE THE FEEDBACK LOOP</Badge><h2>Prediction versus trial.</h2><p>Save the prediction first. Preserve the raw capture. Review acquisition quality before calibration or evaluation.</p></div><div className="judge-trial-actions"><button className="button secondary" disabled={loading} onClick={demonstrate}><FlaskConical size={17}/>{loading?'Loading trial…':'Load generated demonstration'}</button><label>CSV source<select value={origin} onChange={e=>setOrigin(e.target.value)}><option value="generated_stress_test">GENERATED DEMO</option><option value="measured_lab">MEASURED LAB — operator declaration</option></select></label><label>Upload CSV (time_us, voltage_kv)<input type="file" accept=".csv" disabled={loading} onChange={e=>{const file=e.target.files?.[0];if(file)upload(file,origin);e.target.value=''}}/></label></div><p className="panel-note">Judge upload uses µs and kV with zero baseline and onset. Use Trial calibrator for other units, delayed or negative-baseline captures.</p>{activeTrial?<><div className="judge-source-banner"><SourceBadge trial={activeTrial}/><strong>{activeTrial.source_type==='measured_lab'?'Operator-labeled laboratory capture':'GENERATED DEMONSTRATION — NOT LABORATORY EVIDENCE'}</strong></div><EngineeringChart waveform={candidate.waveform} measured={activeTrial.comparison_waveform||activeTrial.waveform} target={judge?.target_waveform} height={290}/><div className="table-wrap"><table><thead><tr><th>Metric</th><th>Saved prediction</th><th>Uploaded trial</th></tr></thead><tbody>{['front_us','tail_us','crest_kv'].map(k=><tr key={k}><td>{k.replaceAll('_',' ')}</td><td>{fmt(candidate.hybrid[k],4)}</td><td>{fmt(activeTrial.measured[k],4)}</td></tr>)}</tbody></table></div><p className="judge-caveat">Acquisition review: {activeTrial.quality?.status||'unknown'}. {activeTrial.quality?.calibration_allowed?'Eligible for scoped local correction.':'Review required before calibration.'} Generated data is excluded from laboratory accuracy.</p></>:<div className="evidence-empty"><FlaskConical size={30}/><h3>No trial selected for this candidate.</h3><p>Load a clearly labeled demonstration or upload an actual capture.</p></div>}<Link className="button secondary" href="/trial-calibrator/">Open full trial calibration and accuracy review</Link></>}
      {step===6&&candidate&&judge&&<div className="judge-summary"><ShieldCheck size={38}/><h2>Every recommendation carries its evidence.</h2><div className="evidence-checks">{[['Synthetic benchmark',w.source?.dataset_hash_matches_frozen_model?'AVAILABLE · HASH VERIFIED':'NOT VERIFIED'],['Independent circuit cross-check',candidate.circuit_crosscheck?'AVAILABLE':'NOT VERIFIED'],['Counted hardware constraints',candidate.front_network.inventory_feasible&&candidate.tail_network.inventory_feasible?'CHECKED':'UNKNOWN'],['ML support check',candidate.ood.state],['Measured laboratory captures',String(judge.laboratory.measured_captures)],['Measured evaluation of this setup',candidate.evidence.evaluation_ids.length?'AVAILABLE · REVIEW ERRORS':'PENDING']].map(([name,status])=><div key={name}><span>{name}</span><Badge>{status}</Badge></div>)}</div><p>The next evidence comes from verified stock, instrumented trial shots and independent measured evaluation.</p><div className="heading-actions"><Link href="/laboratory-evidence/" className="button secondary">Laboratory readiness</Link><a href={apiUrl(`/api/runs/${judge.id}/report`)} target="_blank" rel="noreferrer" className="button primary">Open engineering report <ArrowRight size={16}/></a></div></div>}
    </section><div className="judge-navigation"><button className="button secondary" disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft size={16}/>Back</button><span>{step+1} / {steps.length} · {steps[step]}</span><button className="button primary" disabled={step===6||(step===1&&(!judge||requestEdited))} onClick={()=>setStep(step+1)}>Next<ArrowRight size={16}/></button></div>
  </div>;
}
