'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,Download,GitCompareArrows,LoaderCircle} from 'lucide-react';
import {api,apiUrl,Data,fmt,post} from '@/lib/api';
import {Badge,Panel,Status,useWorkspace} from './workspace';

export default function SetupTransitionPlanner({run}:{run:Data}) {
  const {setSelected}=useWorkspace();
  const [history,setHistory]=useState<Data[]>([]),[baselineId,setBaselineId]=useState(''),[candidateId,setCandidateId]=useState('');
  const [baseline,setBaseline]=useState<Data|null>(null),[result,setResult]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;setResult(null);api('/api/runs').then(rows=>{if(active)setHistory(rows)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[run.id]);
  useEffect(()=>{let active=true;setBaseline(null);setCandidateId('');setResult(null);if(baselineId)api(`/api/runs/${baselineId}`).then(r=>{if(active){setBaseline(r);setCandidateId(r.candidates[0]?.id||'')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[baselineId]);
  const compatible=history.filter(r=>r.inputs.profile_id===run.inputs.profile_id&&r.inputs.layout_id===run.inputs.layout_id);
  const reviewed=result?.target.run_id===run.id&&result?.baseline.run_id===baselineId&&result?.baseline.candidate_id===candidateId?result:null;
  const closest=reviewed?.options.find((o:Data)=>o.candidate_id===reviewed.closest_nominal_candidate_id);
  async function compare(){setBusy(true);setError('');setResult(null);try{setResult(await post(`/api/runs/${run.id}/setup-transitions`,{baseline_run_id:baselineId,baseline_candidate_id:candidateId}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <Panel title="Plan changes from a saved setup" action={<Badge tone="amber">Confirm installed hardware</Badge>}>
    <p className="panel-note">Choose the saved plan that represents your current setup. Compare resistor, active-stage and charging changes with this run’s alternatives. This is a planning aid; saved plans do not authenticate the actual installed equipment.</p>
    <div className="two-fields"><label className="field"><span>Baseline saved run</span><select value={baselineId} onChange={e=>{setBaselineId(e.target.value);setError('')}}><option value="">Choose a matching generator and layout</option>{compatible.map(r=><option key={r.id} value={r.id}>{r.id} · {r.inputs.impulse_type} · {fmt(r.inputs.test_kv,0)} kV</option>)}</select></label><label className="field"><span>Baseline candidate</span><select value={candidateId} disabled={!baseline} onChange={e=>{setCandidateId(e.target.value);setResult(null)}}>{!baseline&&<option value="">Select a saved run first</option>}{baseline?.candidates.map((c:Data)=><option key={c.id} value={c.id}>Rank {c.rank} · {c.settings.stages} stages · Rf {fmt(c.settings.front_r_stage,2)} Ω · Rt {fmt(c.settings.tail_r_stage,2)} Ω</option>)}</select></label></div>
    <button className="button secondary" disabled={busy||!baseline||!candidateId} onClick={compare}>{busy?<LoaderCircle className="spin" size={15}/>:<GitCompareArrows size={15}/>} Compare setup changes</button>
    {error&&<div className="alert error" role="alert">{error}</div>}
    {reviewed&&<div className="trial-quality"><div className="heading-actions"><strong>{reviewed.eligible_count} nominally passing options · original ranking retained</strong><div className="heading-actions"><a className="button secondary" href={apiUrl(`/api/setup-transitions/${reviewed.id}/report`)} target="_blank" rel="noreferrer"><Download size={14}/> Printable change plan</a><a className="button text-button" href={apiUrl(`/api/setup-transitions/${reviewed.id}/json`)}>Audit JSON</a></div></div>
      <p className="panel-note">Preference: {reviewed.priority.join(' → ')}.</p>
      <div className="alert compact"><span>{reviewed.review}</span></div>
      <div className="table-wrap"><table><thead><tr><th>Original rank</th><th>Nominal model / stock / rating checks</th><th>Changed front/tail plans</th><th>Active stages added / deactivated</th><th>Shared-stage part changes</th><th>Charge Δ kV/stage</th><th>Separate challenge</th><th>Uncertainty</th></tr></thead><tbody>{reviewed.options.map((o:Data)=><tr className={o.candidate_id===reviewed.closest_nominal_candidate_id?'highlight-row':''} key={o.candidate_id}><td>Rank {o.original_rank}{o.candidate_id===reviewed.closest_nominal_candidate_id&&<Badge tone="cyan">Closest nominal</Badge>}</td><td>{o.nominal_review.eligible_nominal?'Pass':'Review required'}{o.nominal_review.reasons.map((reason:string)=><small className="block negative" key={reason}>{reason}</small>)}</td><td>{o.changed_network_families} / 2</td><td>{o.active_stages_added} / {o.active_stages_deactivated}</td><td>{o.shared_stage_part_changes}</td><td>{o.charge_delta_kv_stage>0?'+':''}{fmt(o.charge_delta_kv_stage,3)}</td><td>{o.verification?`${o.verification.passed}/${o.verification.total}`:'Not recorded'}</td><td><Status value={o.uncertainty_status}/></td></tr>)}</tbody></table></div>
      {closest&&<><p className="panel-note">Closest nominal option: original rank {closest.original_rank}. Charge change {fmt(closest.charge_delta_pct,2)}%. Model and challenge checks remain simulations.</p><div className="bottom-grid">{Object.entries(closest.networks).map(([name,value])=>{const network=value as Data;return <div key={name}><strong>{name==='front'?'Front':'Tail'}: {network.baseline_topology} → {network.target_topology}</strong><p className="panel-note">{network.shared_stage_banks_to_review} shared-stage connection plans need review. Newly active and deactivated stage parts are shown separately in the printable plan.</p><div className="table-wrap"><table><thead><tr><th>Value</th><th>Before /stage</th><th>After /stage</th><th>Retained shared</th><th>Added shared</th><th>Removed shared</th></tr></thead><tbody>{network.parts.map((part:Data)=><tr key={part.ohm}><td>{fmt(part.ohm,2)} Ω</td><td>{part.baseline_per_stage}</td><td>{part.target_per_stage}</td><td>{part.retained_on_shared_stages}</td><td>{part.added_on_shared_stages}</td><td>{part.removed_from_shared_stages}</td></tr>)}</tbody></table></div></div>})}</div><Link href="/" className="button text-button" onClick={()=>setSelected(run.candidates.findIndex((c:Data)=>c.id===closest.candidate_id))}>Inspect closest nominal option <ArrowRight size={14}/></Link></>}
      <p className="panel-note">{reviewed.scope}</p>
    </div>}
  </Panel>
}
