'use client';
import {createContext,useContext,useEffect,useState,ReactNode,useCallback} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {Activity,ArrowUpRight,Blocks,ChartNoAxesCombined,Check,ChevronRight,CircleHelp,FlaskConical,GitCompareArrows,History,Radio,RefreshCw,ShieldCheck,SlidersHorizontal,Unplug,Zap} from 'lucide-react';
import {api,Data,initialInputs,post,apiUrl} from '@/lib/api';
type Store={profiles:Data[];run:Data|null;candidate:Data|null;selected:number;setSelected:(v:number)=>void;inputs:Data;setInputs:(v:Data)=>void;busy:boolean;error:string;setError:(v:string)=>void;optimize:(values?:Data)=>Promise<Data|null>;loadRun:(id:string)=>Promise<void>;online:boolean|null;source:Data|null;trial:Data|null;setTrial:(v:Data|null)=>void;calibration:Data|null;setCalibration:(v:Data|null)=>void;};
const Context=createContext<Store|null>(null);
export const useWorkspace=()=>useContext(Context)!;
export function Workspace({children}:{children:ReactNode}){const [profiles,setProfiles]=useState<Data[]>([]),[run,setRun]=useState<Data|null>(null),[selected,setSelected]=useState(0),[inputs,setInputs]=useState<Data>(initialInputs),[busy,setBusy]=useState(false),[error,setError]=useState(''),[online,setOnline]=useState<boolean|null>(null),[source,setSource]=useState<Data|null>(null),[trial,setTrial]=useState<Data|null>(null),[calibration,setCalibration]=useState<Data|null>(null);const path=usePathname();
const accept=useCallback((r:Data)=>{setRun(r);setSelected(0);setInputs(r.inputs);localStorage.setItem('impulsetwin-last-run',r.id);},[]);
const loadRun=useCallback(async(id:string)=>{setBusy(true);setError('');try{accept(await api(`/api/runs/${id}`))}catch(e){setError((e as Error).message)}finally{setBusy(false)}},[accept]);
const optimize=useCallback(async(values?:Data)=>{setBusy(true);setError('');try{const r=await post('/api/optimize',values||inputs);accept(r);return r}catch(e){setError((e as Error).message);return null}finally{setBusy(false)}},[inputs,accept]);
useEffect(()=>{let alive=true;Promise.allSettled([api('/api/health'),api('/api/generator-profiles'),api('/api/source-status')]).then(async results=>{if(!alive)return;setOnline(results[0].status==='fulfilled');if(results[1].status==='fulfilled')setProfiles(results[1].value);if(results[2].status==='fulfilled')setSource(results[2].value);if(results[0].status!=='fulfilled'){setError('The local engineering service is unavailable. Start the backend, then reconnect.');return;}const id=localStorage.getItem('impulsetwin-last-run');if(id){try{const saved=await api(`/api/runs/${id}`);if(alive)accept(saved);}catch{localStorage.removeItem('impulsetwin-last-run')}}});return()=>{alive=false}},[accept]);
const nav=[['/judge/','Judge Mode',Zap],['/','Optimizer',SlidersHorizontal],['/laboratory-evidence/','Laboratory Evidence',ShieldCheck],['/hardware-verification/','Hardware Verification',Blocks],['/experiment-timeline/','Experiment Timeline',History],['/search-quality/','Search Quality',ChartNoAxesCombined],['/model-lab/','Model lab',ChartNoAxesCombined],['/profiles/','Generator profiles',Blocks],['/trial-calibrator/','Trial calibrator',FlaskConical],['/runs/','Run history',History],['/compare/','Compare settings',GitCompareArrows]] as const;
return <Context.Provider value={{profiles,run,candidate:run?.candidates?.[selected]||null,selected,setSelected,inputs,setInputs,busy,error,setError,optimize,loadRun,online,source,trial,setTrial,calibration,setCalibration}}><div className="app-shell"><aside className="sidebar"><Link className="brand" href="/" aria-label="ImpulseTwin AI home" title="ImpulseTwin AI home"><div className="brand-icon"><Zap size={23} strokeWidth={1.6}/></div><div>ImpulseTwin<span>AI ENGINEERING STUDIO</span></div></Link><div className="workspace-label"><span className="status-dot"/> POWERnext · Track 01</div><div className="nav-label">WORKSPACE</div><nav>{nav.map(([href,name,Icon])=><Link key={href} aria-current={path.replace(/\/$/,'')===href.replace(/\/$/,'')?'page':undefined} aria-label={name} title={name} className={`nav-item ${path.replace(/\/$/,'')===href.replace(/\/$/,'')?'active':''}`} href={href}><Icon size={18}/><span>{name}</span>{path.replace(/\/$/,'')===href.replace(/\/$/,'')&&<ChevronRight size={14}/>}</Link>)}</nav><div className="sidebar-bottom"><div className="local-card"><Radio size={17}/><div><strong>Local engineering service</strong><span>Local inference · Offline capable</span></div></div><a className="source-link" href={apiUrl('/api/documents/source_reconciliation')} target="_blank" rel="noreferrer"><CircleHelp size={16}/> Source reconciliation <ArrowUpRight size={14}/></a><div className="profile-avatar"><span>HV</span><div>Engineering workspace<small>Decision support · v1.0</small></div><ShieldCheck size={17}/></div></div></aside><div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={13}/><strong>{nav.find(([href])=>path.replace(/\/$/,'')===href.replace(/\/$/,''))?.[1]||'Optimizer'}</strong></div><div className="topbar-right"><span className="quiet">Synthetic benchmark · Lab validation pending</span><span className={`connection ${online?'connected':''}`}>{online?<span className="status-dot"/>:<Unplug size={13}/>} {online?'Local engine online':online===null?'Connecting':'Engine offline'}</span>{online===false&&<button className="icon-button" aria-label="Reconnect backend" onClick={()=>location.reload()}><RefreshCw size={15}/></button>}</div></header><main>{children}</main><footer><span><ShieldCheck size={13}/> Engineer verification required before laboratory setup.</span><span>Physics → Hardware search → Evidence review → Trial feedback</span></footer></div></div></Context.Provider>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge badge-${tone}`}>{children}</span>}
export function Status({value}:{value:string}){return <Badge tone={value?.includes('ROBUST')?'green':value==='FAIL'?'red':'amber'}>{value?.includes('ROBUST')&&<Check size={11}/>} {value||'Unverified'}</Badge>}
export function Panel({title,eyebrow,action,children,className='',id}:{title?:string;eyebrow?:string;action?:ReactNode;children:ReactNode;className?:string;id?:string}){return <section id={id} className={`panel ${className}`}>{title&&<div className="panel-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{action}</div>}{children}</section>}
export function PageHeading({title,description,tag,action}:{title:string;description:string;tag?:string;action?:ReactNode}){return <div className="page-heading"><div>{tag&&<div className="eyebrow cyan">{tag}</div>}<h1>{title}<span className="title-dot">.</span></h1><p>{description}</p></div>{action}</div>}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><Activity size={28}/><h3>{title}</h3><p>{children}</p></div>}
